# Generated by Django 2.2.5 on 2019-10-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_acc_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='batch',
            field=models.CharField(blank=True, default='0', max_length=2),
        ),
    ]
