# Generated by Django 2.2.5 on 2019-10-10 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import store.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('is_verified', models.BooleanField(blank=True, default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('price', models.PositiveSmallIntegerField()),
                ('category', models.CharField(choices=[('Bags', 'Bags'), ('Books', 'Books'), ('Shoes', 'Shoes'), ('Cloths', 'Cloths'), ('Utensils', 'Utensils'), ('Jewelries', 'Jewelries'), ('Cosmetics', 'Cosmetics'), ('Furniture', 'Furniture'), ('Electronics', 'Electronics'), ('Mobile Phones', 'Mobile Phones'), ('Laptop Computers', 'Laptop Computers')], max_length=25)),
                ('quantity', models.PositiveSmallIntegerField(default=2)),
                ('front_photo', models.ImageField(default='default/item.jpg', upload_to=store.models.front_photo_path)),
                ('back_photo', models.ImageField(default='default/item.jpg', upload_to=store.models.back_photo_path)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('orders', models.ManyToManyField(related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Store')),
            ],
        ),
    ]
