# Generated by Django 2.2.5 on 2019-10-12 11:04

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20191010_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='back_photo',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='front_photo',
        ),
        migrations.CreateModel(
            name='CloudinaryPhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Stock')),
            ],
        ),
    ]
