# Generated by Django 2.2.5 on 2019-10-13 06:05

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20191012_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudinaryPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.Stock')),
            ],
        ),
        migrations.DeleteModel(
            name='CloudinaryPhotos',
        ),
    ]
