# Generated by Django 2.2.5 on 2019-10-10 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0001_initial'),
        ('interest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('stock', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='store.Stock')),
            ],
        ),
    ]
