# Generated by Django 2.2.5 on 2019-10-05 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import items.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('available', models.BooleanField(blank=True, default=True)),
                ('category', models.CharField(choices=[('Bags', 'Bags'), ('Books', 'Books'), ('Shoes', 'Shoes'), ('Cloths', 'Cloths'), ('Utensils', 'Utensils'), ('Jewelries', 'Jewelries'), ('Cosmetics', 'Cosmetics'), ('Furniture', 'Furniture'), ('Electronics', 'Electronics'), ('Mobile Phones', 'Mobile Phones'), ('Laptop Computers', 'Laptop Computers')], max_length=25)),
                ('front_photo', models.ImageField(default='default/item.jpg', upload_to=items.models.front_photo_path)),
                ('back_photo', models.ImageField(default='default/item.jpg', upload_to=items.models.back_photo_path)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('owner_confirmation', models.BooleanField(default=False)),
                ('buyer_confirmation', models.BooleanField(default=False)),
                ('booked_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_booked_for', to=settings.AUTH_USER_MODEL, verbose_name='Booked for')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
