# Generated by Django 2.2.5 on 2019-10-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20191015_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('bags', 'Bags'), ('books', 'Books'), ('shoes', 'Shoes'), ('cloths', 'Cloths'), ('utensils', 'Utensils'), ('jewelries', 'Jewelries'), ('cosmetics', 'Cosmetics'), ('furniture', 'Furniture'), ('electronics', 'Electronics'), ('phones', 'Mobile Phones'), ('laptops', 'Laptop Computers')], max_length=25),
        ),
    ]
