# Generated by Django 2.2.5 on 2019-10-05 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(5, '5 stars'), (4, '4 stars'), (3, '3 stars'), (2, '2 stars'), (1, '1 star')], default=0)),
                ('comment', models.TextField(default='')),
                ('review_time', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Reviewer')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userreview_user', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed user')),
            ],
            options={
                'verbose_name': 'User Review',
                'verbose_name_plural': 'User Reviews',
            },
        ),
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_count_1', models.IntegerField(default=0)),
                ('star_count_2', models.IntegerField(default=0)),
                ('star_count_3', models.IntegerField(default=0)),
                ('star_count_4', models.IntegerField(default=0)),
                ('star_count_5', models.IntegerField(default=0)),
                ('star_sum', models.IntegerField(default=0)),
                ('review_count', models.IntegerField(default=0)),
                ('current_rating', models.FloatField(default=0)),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Rated User')),
            ],
            options={
                'verbose_name': 'User Rating',
                'verbose_name_plural': 'User Ratings',
            },
        ),
    ]
