# Generated by Django 2.2.5 on 2019-10-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrating',
            name='star_count_1',
        ),
        migrations.RemoveField(
            model_name='userrating',
            name='star_count_2',
        ),
        migrations.RemoveField(
            model_name='userrating',
            name='star_count_3',
        ),
        migrations.RemoveField(
            model_name='userrating',
            name='star_count_4',
        ),
        migrations.RemoveField(
            model_name='userrating',
            name='star_count_5',
        ),
        migrations.AlterField(
            model_name='userreview',
            name='comment',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (0, '0'), (-1, '-1')], default=0),
        ),
    ]
