# Generated by Django 2.2.5 on 2019-10-29 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20191029_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreview',
            name='rating',
            field=models.IntegerField(choices=[(1, '+1'), (0, '0'), (-1, '-1')], default=0),
        ),
    ]
